import { createElement } from 'lwc';
import Ucl_RunHerokuServiceManually from 'c/ucl_RunHerokuServiceManually';

describe('c-ucl-run-heroku-service-manually', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ucl-run-heroku-service-manually', {
            is: Ucl_RunHerokuServiceManually
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});